package com.opengpt.config

import com.opengpt.auth.TokenStore
import jakarta.servlet.FilterChain
import jakarta.servlet.http.HttpServletRequest
import jakarta.servlet.http.HttpServletResponse
import org.slf4j.LoggerFactory
import org.springframework.http.MediaType
import org.springframework.stereotype.Component
import org.springframework.web.filter.OncePerRequestFilter

/**
 * Requires Authorization Bearer local-api-key on /v1 routes.
 * The key is generated by the adapter after ChatGPT OAuth — not an OpenAI Platform key.
 */
@Component
class LocalApiKeyFilter(
    private val tokenStore: TokenStore,
) : OncePerRequestFilter() {
    private val log = LoggerFactory.getLogger(javaClass)

    override fun shouldNotFilter(request: HttpServletRequest): Boolean {
        val path = request.requestURI
        return !path.startsWith("/v1/")
    }

    override fun doFilterInternal(
        request: HttpServletRequest,
        response: HttpServletResponse,
        filterChain: FilterChain,
    ) {
        val expected =
            try {
                tokenStore.requireApiKey()
            } catch (_: Exception) {
                writeError(response, 401, "ChatGPT account authentication required", "authentication_error")
                return
            }

        val provided = extractBearer(request.getHeader("Authorization"))
        if (provided.isNullOrBlank() || !provided.contentEquals(expected)) {
            log.info("Rejected /v1 request: missing or invalid local API key")
            writeError(response, 401, "Invalid API key", "invalid_api_key")
            return
        }

        log.info("Accepted /v1 {} {}", request.method, request.requestURI)
        filterChain.doFilter(request, response)
    }

    private fun extractBearer(header: String?): String? {
        if (header.isNullOrBlank()) return null
        val prefix = "Bearer "
        if (!header.startsWith(prefix, ignoreCase = true)) return header.trim()
        return header.substring(prefix.length).trim()
    }

    private fun writeError(
        response: HttpServletResponse,
        status: Int,
        message: String,
        type: String,
    ) {
        response.status = status
        response.contentType = MediaType.APPLICATION_JSON_VALUE
        response.writer.write(
            """{"error":{"message":"$message","type":"$type"}}""",
        )
    }
}
